import { BaseInputProps } from "../base/base-input-props";

export interface LabeledInputInputProps<T> extends Omit<BaseInputProps<T>, 'id'> { }

export interface LabeledInputProps<T> {
  /**
   * The string to show in the input label
   */
  labelString: string,
  /**
   * The props generated by react-hook-form's registration
   */
  inputProps: LabeledInputInputProps<T>,
  /**
   * The error to display
   */
  errorString?: string,
  /**
   * Class name overrides for the input
   */
  inputClassNames?: string[],
  /**
   * Class name overrides for the label
   */
  labelClassNames?: string[],
  /**
   * Class name overrides for the error
   */
  errorClassNames?: string[],
}